# Generated by Django 5.1 on 2024-08-15 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermedicaldata',
            name='blood_type',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='usermedicaldata',
            name='vitamin_b12',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
