# Generated by Django 5.1 on 2024-08-15 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_usermedicaldata_blood_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermedicaldata',
            name='hemoglobin_level',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='usermedicaldata',
            name='iron_levels',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='userpersonaldata',
            name='weight',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
