# Generated by Django 5.1 on 2024-08-15 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_usermedicaldata_hemoglobin_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdietrydata',
            name='diet_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='userdietrydata',
            name='region',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
